#:schema https://typst-community.github.io/json-schemas/docs/typst.schema.json

[package]
name = "upsa-bolivia-thesis"
version = "0.1.0"
compiler = "0.15.0"
repository = "https://github.com/jassielof/upsa-bolivia-thesis-template"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "Apache-2.0"
description = "Plantilla para la elaboración de tesis (trabajos de grado) de la Universidad Privada de Santa Cruz de la Sierra (UPSA), Bolivia."
keywords = [
  "UPSA",
  "Universidad Privada de Santa Cruz de la Sierra",
  "Bolivia",
  "tesis",
  "trabajos de grado",
  "documentos de grado",
  "TFG",
]
categories = ["thesis"]
disciplines = ["computer-science", "engineering", "business", "psychology", "communication"]
exclude = ["*.pdf", "reference"]

[template]
path = "template"
entrypoint = "TFG/main.typ"
thumbnail = "thumbnail.png"
